title: Kyanij 
email: kyanij10@gmail.com.com
description: >- # this means to ignore newlines until "baseurl:"
  This is me kyanij Maharjan currently studying Bsc. CSIT from Sagarmatha college of IT.
baseurl: "myblog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
future: true # Show blog post of future date

google_analytics: foo-bar-google-analytics-id # Replace it with your ID starting as UA-

paginate: 6
paginate_path: "/blogs/page:num"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-paginate
